---
- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"

- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Setup/install tasks.
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ''

- name: CA certificates installation
  include_tasks: ca-certificates.yml

- name: Download bouncycastle jars in JRE external libs
  get_url:
    url: 'http://repo2.maven.org/maven2/org/bouncycastle/{{ item }}-jdk15on/{{ bouncycastle_version }}/{{ item }}-jdk15on-{{ bouncycastle_version }}.jar'
    dest: '{{ java_home }}/{{ jre_lib_location }}/{{ item }}-jdk15on-{{ bouncycastle_version }}.jar'
  with_items: '{{ bouncycastle_artifacts }}'
  when: add_bouncycastle and openjdk_version == 8 and java_home is defined and java_home != ''
