---
- name: Remove OracleJDK
  apt:
    name: "{{ oracle_jdk_packages }}"
    state: absent
    purge: true
  when: oracle_jdk_packages is defined

- name: Add jessie-backports if needed
  apt_repository:
      repo: 'deb http://ftp.debian.org/debian jessie-backports main'
      state: present
  when: ansible_distribution_release == 'jessie' and 'openjdk-8-jdk' in java_packages

- name: Ensure Java is installed and is the latest maintenance version (jessie + jdk8).
  apt:
    name: "{{ java_packages }}"
    default_release: jessie-backports
    update_cache: true
    state: "{{ java_packages_expected_state }}"
  when: ansible_distribution_release == 'jessie' and 'openjdk-8-jdk' in java_packages

- name: Add stretch-backports if needed
  apt_repository:
      repo: 'deb http://{{ stretch_backports_repository }}/debian stretch-backports main'
      state: present
  when: ansible_distribution_release == 'stretch' and 'openjdk-11-jdk' in java_packages

- name: Ensure Java is installed and is the latest maintenance version (stretch + jdk11).
  apt:
    name: "{{ java_packages }}"
    default_release: stretch-backports
    update_cache: true
    state: "{{ java_packages_expected_state }}"
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch' and 'openjdk-11-jdk' in java_packages

- name: Ensure Java is installed and is the latest maintenance version .
  apt:
    name: "{{ java_packages }}"
    update_cache: true
    state: "{{ java_packages_expected_state }}"
  when: not(ansible_distribution_release == 'jessie' and 'openjdk-8-jdk' in java_packages) or not(ansible_distribution_release == 'stretch' and 'openjdk-11-jdk' in java_packages)

- name: Get openjdk alternative
  shell: "update-java-alternatives -l | grep java-1.{{ openjdk_version }}.0-openjdk | cut -f -1 -d ' '"
  changed_when: false
  register: openjdk_alternative
  check_mode: false

- name: Set Java alternatives
  command: "update-java-alternatives -s {{ openjdk_alternative.stdout }}"
  changed_when: false
