---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ansible-role-java
      install_cryptography_extension: true
      java_packages:
        - openjdk-11-jdk
      openjdk_version: 11
      ca_certificates:
        certificates:
          - alias: dummy-test
            path: /usr/local/share/ca-certificates/dummy.crt
          - url: google.com
        password: test123
      add_bouncycastle: true
